# Generated by Django 4.2.8 on 2024-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_timestamp',
            field=models.DateTimeField(verbose_name='Дата старта'),
        ),
    ]
