# Generated by Django 4.2.8 on 2024-02-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_products_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='max_users',
            field=models.PositiveIntegerField(default=10, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AddField(
            model_name='products',
            name='min_users',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальное количество студентов'),
        ),
    ]
