# Generated by Django 4.2.8 on 2024-02-29 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0005_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_set', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
    ]
