# Generated by Django 4.2.8 on 2024-03-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_group_count_alter_group_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='count',
        ),
    ]
